### ISSUE TITLE
texture on mlab.surf

### ISSUE THREAD

**Issue by z--m-n** [enthought/mayavi#211]
I am trying to place a texture on a surface (mlab.surf).  Instead, I see a surface with the mean pixel color of that texture image. I would appreciate a confirmation that this great feature (texture on mlab.surf) should still work as advertised and my installed system is to blame.

Similar code worked for me with mayavi 4.3 and vtk5 on a debian system. I did change the arguments passed to tvtk.Texture for it to work with mayavi 4.4.2 and vtk6 (via homebrew and virtenv+pip on OS X).

Thanks in advance!

### EXAMPLE:

```python
from tvtk.api import tvtk
from mayavi import mlab
import numpy as np

mlab.clf()

X,Y=np.mgrid[-1:1:20j,-1:1:20j]
Z = -np.cos(Y*X)+.5

img_filename='anyimage.jpg'
img=tvtk.JPEGReader(file_name=img_filename)
texture=tvtk.Texture(input_connection=img.output_port, interpolate=1)

# following produces a surface with a color that seems to be represent the mean img pixel.
s = mlab.surf(X,Y,Z,color=(1.,1.,1.))
s.actor.actor.mapper.scalar_visibility=False
s.actor.enable_texture=True
s.actor.tcoord_generator_mode='plane'
s.actor.actor.texture=texture

# but the texture itself works!
from mayavi.sources.api import BuiltinSurface
p = mlab.pipeline.surface( BuiltinSurface(source='plane') )
p.actor.actor.texture=texture```

**Comment by z--m-n** [comment]
The issue could be reproduced with the above example on a linux system (ubuntu 14.04, mayavi 4.4.2, vtk 6.0, wxpython 2.8).

**Comment by andrewcollette** [comment]
I can confirm this problem exists on Windows 7 (64-bit) as well.  Textures seem to work on flat objects but I can't get them to work with objects generated using surf or mesh.  Manually constructing a pipeline using `mlab.pipeline.array2d_source` and `mlab.pipeline.scalar_field`, as opposed to the `BuiltinSurface`, also don't work.

Any ideas for a workaround?  I am trying to create a 3D terrain view for an Enthought customer demo next week...

**Comment by z--m-n** [comment]
I could also not get the mlab.pipeline methods to work. The issue may be related, and would explain why also the 'many lines' example is not working on affected systems (see other bug reports).

An elaborate workaround is to draw the terrain pixel by pixel, assuming your terrain map is a geoTIFF or similar 2d matrix source. For instance, as point3d (cubes with scale_factor set to the elevation map grid space, z reduced by half the scale_factor), or as triangular_mesh using two triangles per pixel.

**Comment by farensheep** [comment]
Same for me : mean value data instead of RGB data. I work with Windows 7 and mayavi 4.4.0. I try to downgrade mayavi module to 3.3.1 and it works perfectly !

**Comment by kitchoi** [comment]
#335 should fix the problem.  As you can see [here](https://github.com/enthought/mayavi/pull/335/files#diff-3f50e84588a4a6b096c13b5edb8dff16R255) that a patch to your own build is quite simple.

**Comment by lmkli** [comment]
I don't think the problem is fixed.
I tried the script from #335 and can only get the correct texture on the ''cylinder" case, while the other two are both failed.

**Comment by lmkli** [comment]
updated:
I modified the actor.py file and got the three cases work well.
But the I still can not make it work for 'mesh' object ...

**Comment by eladrich** [comment]
Hi, still experiencing this issue with the surf object (mayavi 4.7.1). Is there any update on this issue?

**Comment by lytyo** [comment]
Same issue here with the triangular_mesh object (mayavi 4.5.0).
